# o erro era porque tenho o postgre instalado na minha máquina (portas colidiram)
services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresql_password
      POSTGRES_DB: imagelite_db
    ports:
      - '5433:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - '15432:80'
    depends_on:
      - db