services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: imagelite_db
    ports:
      - '5433:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - imagelitenetwork
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - '15432:80'
    depends_on:
      - db
    networks:
      - imagelitenetwork
      
  sbootapp:
    build:
      dockerfile: Dockerfile
    container_name: imageliteapi
    restart: on-failure
    depends_on:
      - db
    ports:
      - '8080:8080'
    networks:
      - imagelitenetwork
    environment:
      - PG_HOST=db
      - PG_USERNAME=${PG_USERNAME}
      - PG_PASSWORD=${PG_PASSWORD}
      - PGADMIN_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_PASSWORD=${PGADMIN_PASSWORD}
      


networks:
  imagelitenetwork:
    driver: bridge
