spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_imagelite
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true